<PayScreen>:
    BackgroundLayout:

        Label:
            text: "Unlock Full Version"
            font_size: 22
            bold: True

        Label:
            text: "Pay to unlock premium features"
            opacity: 0.7

        StyledButton:
            text: "Pay (Stub)"
            on_release: root.back()

        StyledButton:
            text: "Back"
            on_release: root.back()
