<SplashScreen>:
    BackgroundLayout:
        orientation: "vertical"
        spacing: "20dp"

        Widget:

        Label:
            text: "Palacharak"
            font_size: 32
            bold: True
            halign: "center"
            valign: "middle"
            text_size: self.size

        Label:
            text: "Loading..."
            font_size: 16
            halign: "center"

        Widget:
